name: Checkov Scan

on:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  checkov_scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install Checkov
      - name: Install Checkov
        run: |
          python -m pip install --upgrade pip
          pip install checkov

      # Step 4: Run Checkov and generate HTML report
      - name: Run Checkov Scan
        run: |
          checkov --directory ${{ github.workspace }} --output html > ${{ github.workspace }}/checkov_report.html || exit 0

      # Step 5: Publish the Checkov HTML report as an artifact
      - name: Publish Checkov HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: checkov-html-report
          path: ${{ github.workspace }}/checkov_report.html
